# Generated by Django 3.0.8 on 2021-05-14 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booling_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_time', models.CharField(max_length=150)),
                ('Adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisor.advisor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
