# Generated by Django 3.0.8 on 2021-05-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_booling_call'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booling_call',
            new_name='Booking_call',
        ),
    ]
